### ISSUE TITLE
create_device always calls NVAPI

### ISSUE THREAD

**Issue by matchang-dt** [shader-slang/slangpy#104]
I tried to run [Your First Function](https://slangpy.shader-slang.org/en/latest/firstfunctions.html) but  I got an error at the following line.

```Python
device = spy.create_device(include_paths=[
        pathlib.Path(__file__).parent.absolute(),
])
```
> Exception has occurred: RuntimeError
> Failed to initialize NVAPI.
> D:\a\sgl\sgl\src\sgl\device\device.cpp(109) in function PipelineCreationAPIDispatcher

My environment is Windows 11pro with AMD Ryzen 7 7730U with Radeon Graphics.
I have the error even if I explicitly specify the type argument as `DeviceType.d3d12`, `DeviceType.vulkan` or `DeviceType.cpu`.

**Comment by ccummingsNV** [comment]
Hi there. I've been through the code and we currently don't disable NVApi for none-NVidia cards on PC. We're currently working on a significant rewrite of the underlying RHI (which will bring with it CUDA support - yay!) and will make sure this dependency is removed. The fix is probably a few weeks away as yet.

**Comment by sleeplessai** [comment]
@ccummingsNV @bmillsNV 
Got it, thanks and look fwd to this.

**Comment by skallweitNV** [comment]
Should be fixed.

**Comment by psruthikNV** [comment]
@skallweitNV Was commit https://github.com/shader-slang/slangpy/commit/07eaf03243d3cf09097acb9f9e6087d488cddb04 intended to be linked with this issue?I could be wrong but it doesn't look like the above commit is related to this issue? I suspect this issue is still occurring with more recent builds of Slangpy (I've hit this in https://github.com/shader-slang/slangpy/issues/228)
